// <auto-generated />
using System;
using ESS.Admin.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESS.Admin.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ess")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESS.Admin.Core.Domain.Administration.Message", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATTACHMENTS");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("ATTEMPTS");

                    b.Property<string>("BccRecipients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BCC_RECIPIENTS");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BODY");

                    b.Property<string>("CcRecipients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CC_RECIPIENTS");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY");

                    b.Property<string>("Recipients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RECIPIENTS");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int")
                        .HasColumnName("RECORD_STATUS");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SENT_DATE");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUBJECT");

                    b.HasKey("RecordId")
                        .HasName("PK_MESSAGES");

                    b.ToTable("MESSAGES");
                });

            modelBuilder.Entity("ESS.Admin.Core.Domain.Administration.User", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("IS_LOCKED");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LAST_NAME");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int")
                        .HasColumnName("RECORD_STATUS");

                    b.HasKey("RecordId")
                        .HasName("PK_USERS");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
