// <auto-generated />
using System;
using ESS.Admin.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESS.Admin.DataAccess.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211213085322_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ESS.Admin.Core.Domain.Administration.Message", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("Attachments")
                        .HasColumnType("TEXT")
                        .HasColumnName("ATTACHMENTS");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ATTEMPTS");

                    b.Property<string>("BccRecipients")
                        .HasColumnType("TEXT")
                        .HasColumnName("BCC_RECIPIENTS");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("BODY");

                    b.Property<string>("CcRecipients")
                        .HasColumnType("TEXT")
                        .HasColumnName("CC_RECIPIENTS");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Recipients")
                        .HasColumnType("TEXT")
                        .HasColumnName("RECIPIENTS");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RECORD_STATUS");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("SENT_DATE");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("SUBJECT");

                    b.HasKey("RecordId")
                        .HasName("PK_MESSAGES");

                    b.ToTable("MESSAGES");
                });

            modelBuilder.Entity("ESS.Admin.Core.Domain.Administration.User", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("RECORD_ID");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("FIRST_NAME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DELETED");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_LOCKED");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LAST_NAME");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RECORD_STATUS");

                    b.HasKey("RecordId")
                        .HasName("PK_USERS");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
